const {
  withInfoPlist,
  withDangerousMod,
  withPodfileProperties,
  withXcodeProject,
  withAppBuildGradle,
  AndroidConfig,
  createRunOncePlugin,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const pkg = require("../package.json");

// Interop note: this service (and the `creeba/chat/0` ALPN in IrohNode) must stay
// identical to desktop/Elysia so mDNS discovery works across apps.
const BONJOUR_SERVICE = "_creebachat._udp";
const DEFAULT_USAGE =
  "Creeba uses the local network to discover nearby peers (encrypted P2P chat).";

// iroh-ffi 1.0: Swift Package + minimum iOS version.
const IROH_URL = "https://github.com/n0-computer/iroh-ffi.git";
// Semantic version (no "v" prefix): SPM maps it to the git tag `v1.0.0`.
const IROH_VERSION = "1.0.0";
const IOS_DEPLOYMENT_TARGET = "17.5";

/** iOS: "local network" permission + Bonjour service (NWBrowser/NWListener). */
const withIosInfoPlist = (config, usage) =>
  withInfoPlist(config, (cfg) => {
    cfg.modResults.NSLocalNetworkUsageDescription =
      cfg.modResults.NSLocalNetworkUsageDescription || usage;
    const services = new Set(cfg.modResults.NSBonjourServices || []);
    services.add(BONJOUR_SERVICE);
    cfg.modResults.NSBonjourServices = Array.from(services);
    return cfg;
  });

/** iOS: iroh-ffi requires iOS 17.5 — for the Pods (via Podfile.properties). */
const withIosPodsDeploymentTarget = (config) =>
  withPodfileProperties(config, (cfg) => {
    cfg.modResults["ios.deploymentTarget"] = IOS_DEPLOYMENT_TARGET;
    return cfg;
  });

// iOS 26 split SwiftUI into `SwiftUI` + `SwiftUICore` (private). The app target
// compiles `ExpoModulesProvider.swift` which imports SwiftUI modules and emits an
// autolink `-framework SwiftUICore` in the app binary → linking fails ("not an
// allowed client"). We disable that autolink on the app target.
const SWIFTUICORE_FLAG =
  "-Xfrontend -disable-autolink-framework -Xfrontend SwiftUICore";

/**
 * iOS: on the app target (project.pbxproj) — set the deployment target (17.5,
 * required by iroh-ffi) and break the SwiftUICore autolink inherited from SwiftUI.
 */
const withIosAppBuildSettings = (config) =>
  withXcodeProject(config, (cfg) => {
    const configurations = cfg.modResults.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(configurations)) {
      const settings = configurations[key].buildSettings;
      if (!settings || !settings.IPHONEOS_DEPLOYMENT_TARGET) continue;

      settings.IPHONEOS_DEPLOYMENT_TARGET = IOS_DEPLOYMENT_TARGET;

      let flags = settings.OTHER_SWIFT_FLAGS;
      if (Array.isArray(flags)) flags = flags.join(" ");
      flags = (flags || "$(inherited)").replace(/^"|"$/g, "");
      if (!flags.includes("SwiftUICore")) {
        settings.OTHER_SWIFT_FLAGS = `"${flags} ${SWIFTUICORE_FLAG}"`;
      }
    }
    return cfg;
  });

/**
 * iOS: declare the iroh-ffi Swift Package SOURCE in the Podfile via the
 * `cocoapods-spm` plugin (the podspec itself depends on `IrohLib/IrohLib`).
 * Prerequisite: `gem install cocoapods-spm` (or add it to the Gemfile).
 */
const withIrohPodfile = (config) =>
  withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfile, "utf8");

      if (!contents.includes("cocoapods-spm")) {
        contents = `plugin 'cocoapods-spm'\n${contents}`;
      }
      if (!contents.includes('spm_pkg "IrohLib"')) {
        contents = contents.replace(
          /(target\s+['"][^'"]+['"]\s+do\b)/,
          `$1\n  spm_pkg "IrohLib", :url => "${IROH_URL}", :version => "${IROH_VERSION}"`,
        );
      }

      // iOS 26: break the SwiftUICore autolink on all pod targets (e.g.
      // `Pods-creeba` compiles `ExpoModulesProvider.swift` which imports SwiftUI
      // modules → autolink propagated to the app dylib). Injected into the
      // `post_install` block generated by Expo.
      if (!contents.includes("creeba-expo: disable SwiftUICore autolink")) {
        const snippet = [
          "",
          "    # creeba-expo: disable SwiftUICore autolink (iOS 26 private framework)",
          "    installer.pods_project.targets.each do |t|",
          "      t.build_configurations.each do |c|",
          "        f = c.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'",
          "        f = f.join(' ') if f.is_a?(Array)",
          "        unless f.include?('SwiftUICore')",
          "          c.build_settings['OTHER_SWIFT_FLAGS'] = f + ' -Xfrontend -disable-autolink-framework -Xfrontend SwiftUICore'",
          "        end",
          "      end",
          "    end",
        ].join("\n");
        contents = contents.replace(
          /(post_install do \|installer\|\n)/,
          `$1${snippet}\n`,
        );
      }

      fs.writeFileSync(podfile, contents);
      return cfg;
    },
  ]);

/** Android: network/multicast permissions required by NsdManager. */
const withAndroidPermissions = (config) =>
  AndroidConfig.Permissions.withPermissions(config, [
    "android.permission.INTERNET",
    "android.permission.ACCESS_NETWORK_STATE",
    "android.permission.ACCESS_WIFI_STATE",
    "android.permission.CHANGE_WIFI_MULTICAST_STATE",
  ]);

// iroh (uniffi) loads its native lib via JNA. The Android variant is the AAR
// (`jni/**/libjnidispatch.so`). Declared at the app level, it guarantees the .so
// is packaged in the APK — otherwise `UnsatisfiedLinkError` at runtime, because
// jniLibs from a library module's @aar dependency are not always merged by AGP.
// Version aligned with what iroh 1.0.0 expects.
const JNA_DEP = 'implementation("net.java.dev.jna:jna:5.15.0@aar")';

/** Android: add the JNA (AAR) dependency to the app to package libjnidispatch.so. */
const withAndroidJna = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") return cfg;
    if (cfg.modResults.contents.includes("net.java.dev.jna:jna")) return cfg;
    cfg.modResults.contents = cfg.modResults.contents.replace(
      /(dependencies\s*\{)/,
      `$1\n    // creeba-expo: JNA (uniffi/iroh) — package jni/**/libjnidispatch.so\n    ${JNA_DEP}`,
    );
    return cfg;
  });

const withCreebaExpo = (config, props = {}) => {
  const usage = props.localNetworkUsageDescription || DEFAULT_USAGE;
  config = withIosInfoPlist(config, usage);
  config = withIosPodsDeploymentTarget(config);
  config = withIosAppBuildSettings(config);
  config = withIrohPodfile(config);
  config = withAndroidPermissions(config);
  config = withAndroidJna(config);
  return config;
};

module.exports = createRunOncePlugin(withCreebaExpo, pkg.name, pkg.version);
